version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 6533:5432
    # healthcheck:
    #   test: ['CMD', 'pg_isready', '-U', 'postgis', '-d', 'postgis']
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - '5555:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: mostafamok.mm@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  database-data:

networks:
  map-templete:
