version: '3'

services:
  database:
    container_name: database
    image: postgis/postgis:14-3.3-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mustafa
      POSTGRES_USER: 'postgis'
      POSTGRES_DB: 'postgis'
    ports:
      - 6543:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgis', '-d', 'postgis']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  map-templete:
